image: Visual Studio 2019
configuration: Release

install:
  - choco install gitversion.portable --version 4.0.0
  - GitVersion /output buildserver

#cache:
#  - src\packages -> src/**/packages.config
#  - C:\ProgramData\chocolatey\bin\OpenCover.Console.exe -> appveyor.yml
#  - C:\ProgramData\chocolatey\bin\coveralls.net.exe -> appveyor.yml
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  COVERALLS_REPO_TOKEN:
    secure: 7apBd6hzfYjVoClqPS+PlHPMqNbUe6Bhlku/45cB2cZiWff4M36qn3B3ibgnRU/+
  CoverityProjectToken:
    secure: 8BZT5bnory1d0llayVIHpbKdpDsfqwnTX6QCOA1LJdw=
  CoverityEmailDistribution:
    secure: bVPyDjOtyByKm9rSo/rjN79B6Z6/pI1hhbhYZHiAJ/E=

before_build:
  - nuget restore src

build_script:
  - ps: .\BuildScripts\AppVeyor-Build.ps1

test: off

artifacts:
  - path: artifacts\coverage.xml

  - path: artifacts\Pretzel.ScriptCs.*.nupkg
    name: Pretzel.ScriptCs.nupkg

  - path: artifacts\Pretzel.ScriptCs.*.zip
    name: Pretzel.ScriptCs.zip

  - path: artifacts\Pretzel.Logic.*.symbols.nupkg
    name: Pretzel.Logic.symbols.nupkg

  - path: artifacts\Pretzel.Logic.*.nupkg
    name: Pretzel.Logic.nupkg

  - path: artifacts\Pretzel.*.nupkg
    name: Pretzel.nupkg

  - path: artifacts\Pretzel.*.zip
    name: Pretzel.zip


deploy:
  - provider: GitHub
    auth_token:
      secure: piWk1xd/YxJK+HJOFwJyBORP+Go1p4XO6148zeePdyVEGPxk4wGXk5tP2jYkM4eU
    artifact: Pretzel.zip, Pretzel.ScriptCs.zip
    description: $(releaseDescription)
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://chocolatey.org/
    api_key:
      secure: 2GBJF71EQfU+kIL5NHVM4wYoCRcFf/gM/voNIgud8vDWUE+uA1ye/hRWjJPQWA5w
    skip_symbols: true
    artifact: Pretzel.nupkg, Pretzel.ScriptCs.nupkg
    on:
      appveyor_repo_tag: true
      
  - provider: NuGet
    api_key:
      secure: NmM24h0TPsfINvy/1Qr4iJkmRjVztuY5umCJ6mzpxSjvuKl48AXjGEcgow+iJwL8
    artifact: Pretzel.Logic.nupkg, Pretzel.Logic.symbols.nupkg
    on:
      appveyor_repo_tag: true
